// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKjeLY_w-2ylTkaPfQx49XPMBVfZfg_GI',
    appId: '1:841536705272:web:0951b841413a40428a210d',
    messagingSenderId: '841536705272',
    projectId: 'chat-app-87771',
    authDomain: 'chat-app-87771.firebaseapp.com',
    storageBucket: 'chat-app-87771.appspot.com',
    measurementId: 'G-9G775487Y3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMcY626CCsk7fPPiIZsZi95NHq4THUg_I',
    appId: '1:841536705272:android:480b994def1d57868a210d',
    messagingSenderId: '841536705272',
    projectId: 'chat-app-87771',
    storageBucket: 'chat-app-87771.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkXUHF96BTdK-tip_2gnpnufV_MoaAs1M',
    appId: '1:841536705272:ios:92d99dcf33124d198a210d',
    messagingSenderId: '841536705272',
    projectId: 'chat-app-87771',
    storageBucket: 'chat-app-87771.appspot.com',
    iosClientId: '841536705272-madlq6d0dtboarf38m49taq7eu2meivc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkXUHF96BTdK-tip_2gnpnufV_MoaAs1M',
    appId: '1:841536705272:ios:92d99dcf33124d198a210d',
    messagingSenderId: '841536705272',
    projectId: 'chat-app-87771',
    storageBucket: 'chat-app-87771.appspot.com',
    iosClientId: '841536705272-madlq6d0dtboarf38m49taq7eu2meivc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
